image: python:3.7.4-alpine3.10

pipelines:
  branches:
    develop:
      - step:
          deployment: Dev
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            # - CURRENT_TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - TAG=latest
            - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            - aws configure set aws_secret_access_key "${AWS_ACCESS_KEY}"
            - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin $REGISTRY
            - docker build -t $REGISTRY/$IMAGE:$TAG .
            - docker push $REGISTRY/$IMAGE:$TAG