version: "3.9"
services:
  core:
    build: .
    volumes:
      - ./apps/core:/usr/src/apps/core
      - ./common:/usr/src/common
    networks:
      - backend
    env_file:
      - .env
    command: "start -w core"
    depends_on:
      postgres:
        condition: service_healthy

  auth:
    build: .
    volumes:
      - ./apps/auth:/usr/src/apps/auth
      - ./common:/usr/src/common
    networks:
      - backend
    env_file:
      - .env    
    command: "start -w auth"
    depends_on:
      postgres:
        condition: service_healthy

  bc-listener:
    build: .
    volumes:
      - ./apps/bc-listener:/usr/src/apps/bc-listener
    networks:
      - backend
    env_file:
      - .env
    command: "start -w bc-listener"

  notifier:
    build: .
    volumes:
      - ./apps/notifier:/usr/src/apps/notifier
    networks:
      - backend
    env_file:
      - .env
    command: "start -w notifier"

  api-gateway:
    build: .
    volumes:
      - ./apps/api-gateway:/usr/src/apps/api-gateway
      - ./common:/usr/src/common
    networks:
      - backend
    env_file:
      - .env
    command: "start -w api-gateway"

    ports:
      - ${API_GATEWAY_PORT}:3000

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - backend
    ports:
      - ${REDIS_PORT}:6379

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "--dbname=${POSTGRES_DB}"]
    networks:
      - backend
    ports:
      - ${DB_PORT}:5432

networks:
  backend:

volumes:
  pg-data:
  redis-data: