export const webhookData: string[] = [
  'accounts',
  'kyc_document_checks',
  'cip_checks',
  'contributions',
  'funds_transfers',
  'disbursements',
  'aml-checks',
  'account-cash-transfers',
  'contacts',
  'contingent-holds',
  'disbursement-authorizations',
  'funds-transfers',
  'asset-transfers',
];
